---
- name: 'Update repositories and upgrade system'
  apt:
    name: "*"    
    state: latest
    update_cache: yes
  become: yes

- name: 'Install Spotify Repository'
  block:
    - apt_key:
        keyserver: keyserver.ubuntu.com
        id: "{{ item }}"
      with_items:
        - 0DF731E45CE24F27EEEB1450EFDC8610341D9410
        - 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
    - apt_repository:
        repo: deb http://repository.spotify.com stable non-free

  become: yes